pub struct NpcSeed {
    pub id: &'static str,
    pub name: &'static str,
    pub age: Option<i32>,
    pub gender: Option<&'static str>,
    pub archetype: &'static str,
    pub residence: &'static str,
    pub role: &'static str,
    pub sanity: i32,
    pub trust: i32,
    pub is_rememberer: i32,
    pub secret: Option<&'static str>,
    pub hook: Option<&'static str>,
}

pub static NPC_SEEDS: &[NpcSeed] = &[
    NpcSeed { id: "lloyd_becker", name: "Lloyd Becker", age: Some(54), gender: Some("Man"), archetype: "sheriff", residence: "town", role: "Sheriff, ex-MP", sanity: 70, trust: 60, is_rememberer: 0,
        secret: Some("Shot his wife during her breakdown six months ago"),
        hook:   Some("Quiet, weary; drinks lukewarm coffee; talks to a dead chaplain in his head") },
    NpcSeed { id: "maria_vance", name: "Maria Vance", age: Some(49), gender: Some("Woman"), archetype: "colony-leader", residence: "colony_house", role: "Colony leader, ex-EMT", sanity: 65, trust: 55, is_rememberer: 0,
        secret: Some("Her sister was the first death here — she traded the coat for a talisman"),
        hook:   Some("Smiles a lot; sleeps three hours a night") },
    NpcSeed { id: "han_lee", name: "Han Lee", age: Some(28), gender: Some("Man"), archetype: "deputy", residence: "town", role: "Deputy, ex-bike messenger", sanity: 65, trust: 70, is_rememberer: 0,
        secret: Some("In love with Mara Aoki"),
        hook:   Some("Eager, loyal; calls Becker 'boss'") },
    NpcSeed { id: "father_patel", name: "Father Idris Patel", age: Some(51), gender: Some("Man"), archetype: "priest", residence: "town", role: "Town priest", sanity: 60, trust: 65, is_rememberer: 0,
        secret: Some("Buried a bag in the woods on arrival: a bottle, a child's shoe"),
        hook:   Some("Believes the town is the 74th book of an unwritten scripture") },
    NpcSeed { id: "old_ren", name: "Old Ren", age: Some(70), gender: Some("Man"), archetype: "victor-analog", residence: "colony_house", role: "Maintenance", sanity: 40, trust: 50, is_rememberer: 0,
        secret: Some("Saw the original sacrifice as a boy; refuses to look at the bottle tree"),
        hook:   Some("Speaks in clipped fragments; knows the song; will not sing it") },
    NpcSeed { id: "mara_aoki", name: "Mara Aoki", age: Some(36), gender: Some("Woman"), archetype: "doctor", residence: "town", role: "Doctor", sanity: 60, trust: 70, is_rememberer: 0,
        secret: Some("Engaged to Nessa; believes she may be pregnant"),
        hook:   Some("Calm voice; counts buttons in her pockets") },
    NpcSeed { id: "nessa_whitcomb", name: "Nessa Whitcomb", age: Some(33), gender: Some("Woman"), archetype: "nurse", residence: "town", role: "Pediatric nurse, bus arrival", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Was leaving Mara when the bus arrived"),
        hook:   Some("Quiet; lights candles at dusk") },
    NpcSeed { id: "hollis_bray", name: "Hollis Bray", age: Some(41), gender: Some("Man"), archetype: "volatile-mechanic", residence: "colony_house", role: "Mechanic", sanity: 30, trust: 30, is_rememberer: 0,
        secret: Some("Killed a man in 1998; thinks the town is his punishment"),
        hook:   Some("Quick-tempered; carries a wrench like a rosary") },
    NpcSeed { id: "tian_lan_chen", name: "Tian-Lan Chen", age: Some(62), gender: Some("Woman"), archetype: "diner-cook", residence: "town", role: "Diner cook", sanity: 60, trust: 70, is_rememberer: 0,
        secret: Some("Her son Han doesn't know his father isn't dead"),
        hook:   Some("The diner is her cathedral; feeds everyone") },
    NpcSeed { id: "bing_chen", name: "Bing Chen", age: Some(68), gender: Some("Man"), archetype: "elder-fading", residence: "town", role: "Diner co-owner", sanity: 35, trust: 50, is_rememberer: 0,
        secret: Some("Early dementia; sometimes calls Becker 'Daniel'"),
        hook:   Some("Plays chess against himself on the porch") },
    NpcSeed { id: "ezra_stone", name: "Ezra Stone", age: Some(22), gender: Some("Man"), archetype: "estranged-son", residence: "colony_house", role: "Tattoo artist", sanity: 60, trust: 50, is_rememberer: 0,
        secret: Some("Becker's estranged son; neither has acknowledged it"),
        hook:   Some("Draws the same symbol in charcoal, over and over") },
    NpcSeed { id: "fatou_ndiaye", name: "Fatou N'Diaye", age: Some(26), gender: Some("Woman"), archetype: "fatima-analog", residence: "colony_house", role: "Yoga teacher, pregnant", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Pregnancy progresses impossibly fast"),
        hook:   Some("Hungry; always hungry") },
    NpcSeed { id: "bram_mathers", name: "Bram Mathers", age: Some(44), gender: Some("Man"), archetype: "father-engineer", residence: "town", role: "Father, ex-engineer", sanity: 60, trust: 70, is_rememberer: 0,
        secret: Some("Lost a daughter before arrival"),
        hook:   Some("Maps the woods on graph paper; maps don't match day to day") },
    NpcSeed { id: "cora_mathers", name: "Cora Mathers", age: Some(40), gender: Some("Woman"), archetype: "tabitha-decoy", residence: "town", role: "Mother", sanity: 55, trust: 65, is_rememberer: 0,
        secret: Some("Hums a tune she doesn't know she knows"),
        hook:   Some("Vivid red-herring for the Rememberer mechanic") },
    NpcSeed { id: "lily_mathers", name: "Lily Mathers", age: Some(16), gender: Some("Girl"), archetype: "restless-teen", residence: "town", role: "Teen", sanity: 45, trust: 50, is_rememberer: 0,
        secret: Some("Writes letters to a boy who doesn't exist"),
        hook:   Some("Smokes hand-rolled cigarettes from Colony") },
    NpcSeed { id: "theo_mathers", name: "Theo Mathers", age: Some(8), gender: Some("Boy"), archetype: "seer-child", residence: "town", role: "Child", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Sees the Boy in Grey"),
        hook:   Some("Tells Cora about 'the boy' — she doesn't see him") },
    NpcSeed { id: "iris_calloway", name: "Iris Calloway", age: Some(31), gender: Some("Woman"), archetype: "rememberer-1", residence: "town", role: "Bookkeeper, bus arrival", sanity: 50, trust: 50, is_rememberer: 1,
        secret: Some("Reincarnation of Mirela, who arrived in 1953 and came close to saving the children"),
        hook:   Some("Hums the violin lullaby in her sleep; flinches at bottle trees") },
    NpcSeed { id: "tobias_greer", name: "Tobias Greer", age: Some(38), gender: Some("Man"), archetype: "bartender", residence: "town", role: "Bartender", sanity: 55, trust: 50, is_rememberer: 0,
        secret: Some("His 'wife' never existed; he invented her completely"),
        hook:   Some("Pours doubles; never charges") },
    NpcSeed { id: "nora_pell", name: "Nora Pell", age: Some(27), gender: Some("Woman"), archetype: "sound-engineer", residence: "colony_house", role: "Sound engineer, bus arrival", sanity: 50, trust: 45, is_rememberer: 0,
        secret: Some("Her dream recordings include sounds from before she arrived"),
        hook:   Some("Listens to static at 3am") },
    NpcSeed { id: "sister_agnes", name: "Sister Agnes", age: Some(67), gender: Some("Woman"), archetype: "elder-faith", residence: "town", role: "Retired nun", sanity: 65, trust: 55, is_rememberer: 0,
        secret: Some("Lost her faith thirty years ago; got it back here"),
        hook:   Some("Mends clothes for everyone") },
    NpcSeed { id: "wallace_doone", name: "Wallace Doone", age: Some(59), gender: Some("Man"), archetype: "bureaucrat-clinger", residence: "town", role: "Postmaster (no mail)", sanity: 40, trust: 45, is_rememberer: 0,
        secret: Some("Files imaginary reports daily"),
        hook:   Some("Routine as defense against terror") },
    NpcSeed { id: "sasha_marlow", name: "Sasha Marlow", age: Some(19), gender: Some("Woman"), archetype: "wildcard", residence: "colony_house", role: "Drifter", sanity: 45, trust: 30, is_rememberer: 0,
        secret: Some("Sole survivor of a bus crash before she reached the town"),
        hook:   Some("Cuts her own hair with a knife") },
    NpcSeed { id: "marcus_holloway", name: "Marcus Holloway", age: Some(47), gender: Some("Man"), archetype: "ex-cop", residence: "colony_house", role: "Ex-cop", sanity: 55, trust: 50, is_rememberer: 0,
        secret: Some("Doesn't believe the rules apply to him"),
        hook:   Some("Carries a badge nobody asked for") },
    NpcSeed { id: "yusra_khan", name: "Yusra Khan", age: Some(35), gender: Some("Woman"), archetype: "carpenter", residence: "town", role: "Carpenter", sanity: 60, trust: 60, is_rememberer: 0,
        secret: Some("Crafts talismans she's not certain work"),
        hook:   Some("Quiet competence") },
    NpcSeed { id: "pip_trent", name: "Eli Trent", age: Some(11), gender: Some("Girl"), archetype: "child-trusting", residence: "town", role: "Child", sanity: 65, trust: 80, is_rememberer: 0,
        secret: Some("Sees the Boy in Grey; has not told anyone"),
        hook:   Some("Plays cat's cradle on the diner steps") },
    NpcSeed { id: "marta_vega", name: "Marta Vega", age: Some(38), gender: Some("Woman"), archetype: "schoolteacher", residence: "town", role: "Schoolteacher", sanity: 60, trust: 65, is_rememberer: 0,
        secret: Some("Started classes; nobody comes"),
        hook:   Some("Stubborn hope") },
    NpcSeed { id: "cal_reese", name: "Calvin Reese", age: Some(51), gender: Some("Man"), archetype: "drunk-prophet", residence: "colony_house", role: "Drunk poet", sanity: 35, trust: 35, is_rememberer: 0,
        secret: Some("Occasionally correct in ways he can't explain"),
        hook:   Some("'The town is a sentence and we are the words'") },
    NpcSeed { id: "pastor_wynn", name: "Pastor Daryl Wynn", age: Some(56), gender: Some("Man"), archetype: "rival-faith", residence: "colony_house", role: "Pentecostal, lapsed", sanity: 40, trust: 40, is_rememberer: 0,
        secret: Some("Hates Father Patel; wants to lead in his place"),
        hook:   Some("Sermons on the Colony porch at dawn") },
    NpcSeed { id: "hattie_lin", name: "Hattie Lin", age: Some(73), gender: Some("Woman"), archetype: "historian", residence: "town", role: "Self-appointed historian", sanity: 60, trust: 55, is_rememberer: 0,
        secret: Some("Has a notebook of every arrival's name since she arrived"),
        hook:   Some("Tea-drinker; eyes sharp") },
    NpcSeed { id: "nile_okoye", name: "Nile Okoye", age: Some(29), gender: Some("Man"), archetype: "photographer", residence: "colony_house", role: "Photographer", sanity: 50, trust: 50, is_rememberer: 0,
        secret: Some("His film never develops correctly; images show the wrong people"),
        hook:   Some("Sees patterns in everything") },
    NpcSeed { id: "pearl_adisa", name: "Pearl Adisa", age: Some(67), gender: Some("Woman"), archetype: "elder-doctor", residence: "colony_house", role: "Retired pediatrician", sanity: 55, trust: 65, is_rememberer: 0,
        secret: Some("Does not know Wren is her daughter, who arrived eighteen years ago"),
        hook:   Some("Knits constantly") },
    NpcSeed { id: "rico_voss", name: "Rico Voss", age: Some(33), gender: Some("Man"), archetype: "volatile-trucker", residence: "colony_house", role: "Trucker", sanity: 35, trust: 30, is_rememberer: 0,
        secret: Some("Drove the rig that brought four of these people here"),
        hook:   Some("Blames himself") },
    NpcSeed { id: "greta_halberg", name: "Greta Halberg", age: Some(58), gender: Some("Woman"), archetype: "seamstress", residence: "town", role: "Seamstress", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Was a war photographer before she came here"),
        hook:   Some("Sews the dead's burial clothes") },
    NpcSeed { id: "wren_adisa", name: "Wren Adisa", age: Some(27), gender: Some("Non-binary"), archetype: "rememberer-2", residence: "colony_house", role: "Violinist, busker", sanity: 50, trust: 55, is_rememberer: 1,
        secret: Some("Reincarnation of Caelum, who arrived in 1907 and came close to saving the children"),
        hook:   Some("Knows a song they swear they invented; plays it without knowing why") },
    NpcSeed { id: "dorian_vance", name: "Dorian Vance", age: Some(26), gender: Some("Man"), archetype: "nepotism", residence: "colony_house", role: "Maria's nephew", sanity: 50, trust: 60, is_rememberer: 0,
        secret: Some("Resents being kept safe under Maria's protection"),
        hook:   Some("Wants to lead; hasn't earned it") },
    NpcSeed { id: "june_carter", name: "June Carter", age: Some(44), gender: Some("Woman"), archetype: "locksmith", residence: "town", role: "Locksmith", sanity: 65, trust: 65, is_rememberer: 0,
        secret: Some("Was arrested two days before the road took her"),
        hook:   Some("Lockpicks any door silently; never explains how") },
    NpcSeed { id: "petra_stojan", name: "Petra Stojan", age: Some(51), gender: Some("Woman"), archetype: "architect", residence: "colony_house", role: "Ex-architect", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Drew up a shelter plan nobody read"),
        hook:   Some("Patient to a fault") },
    NpcSeed { id: "saul_bergman", name: "Saul Bergman", age: Some(71), gender: Some("Man"), archetype: "watchmaker", residence: "town", role: "Watchmaker", sanity: 60, trust: 65, is_rememberer: 0,
        secret: Some("His pocket watch stopped at 3:17 the day they arrived"),
        hook:   Some("Believes the watch will start again when they leave") },
    NpcSeed { id: "inez_calderon", name: "Inez Calderón", age: Some(32), gender: Some("Woman"), archetype: "vet", residence: "town", role: "Veterinarian", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("The town has no animals except one cat she fed once; the cat vanished"),
        hook:   Some("Keeps the cat's bowl clean") },
    NpcSeed { id: "beau_lansdale", name: "Beau Lansdale", age: Some(39), gender: Some("Man"), archetype: "ex-firefighter", residence: "colony_house", role: "Ex-firefighter", sanity: 50, trust: 55, is_rememberer: 0,
        secret: Some("Couldn't save someone in a fire before arrival"),
        hook:   Some("Drinks too much; watches every door") },
    NpcSeed { id: "annika_bell", name: "Annika Bell", age: Some(24), gender: Some("Woman"), archetype: "scholar", residence: "colony_house", role: "Ex-grad student, bus arrival", sanity: 55, trust: 45, is_rememberer: 0,
        secret: Some("Her thesis was on liminal folklore; she thinks she's inside a case study"),
        hook:   Some("Asks everyone unsettling questions") },
    NpcSeed { id: "rev_sune", name: "Reverend Mother Sune", age: Some(80), gender: Some("Woman"), archetype: "dark-prophet", residence: "town", role: "Self-appointed sage", sanity: 70, trust: 50, is_rememberer: 0,
        secret: Some("Believes the children must die again for the town to survive"),
        hook:   Some("Speaks at the worst possible moment") },
    NpcSeed { id: "casey_drew", name: "Casey Drew", age: Some(18), gender: Some("Non-binary"), archetype: "runaway", residence: "town", role: "Runaway, bus arrival", sanity: 35, trust: 40, is_rememberer: 0,
        secret: Some("Was running toward the highway when the bus crashed"),
        hook:   Some("Sleeps with a knife under the pillow") },
    NpcSeed { id: "khalid_mansour", name: "Khalid Mansour", age: Some(41), gender: Some("Man"), archetype: "imam", residence: "town", role: "Imam, ex-trucker", sanity: 60, trust: 65, is_rememberer: 0,
        secret: Some("Father Patel's chess partner; quiet rival, public friend"),
        hook:   Some("Has not raised his voice here once") },
    NpcSeed { id: "sissel_hagen", name: "Sissel Hagen", age: Some(30), gender: Some("Woman"), archetype: "midwife", residence: "colony_house", role: "Doula", sanity: 60, trust: 65, is_rememberer: 0,
        secret: Some("Delivered three babies in the town; two were wrong in ways she won't describe"),
        hook:   Some("Central to Fatou's arc") },
    NpcSeed { id: "owen_spivey", name: "Owen Spivey", age: Some(64), gender: Some("Man"), archetype: "backup-medic", residence: "town", role: "Backup medic, nurse", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Refuses to be called doctor"),
        hook:   Some("Backup when Mara is overwhelmed") },
    NpcSeed { id: "tally_mosk", name: "Tally Mosk", age: Some(17), gender: Some("Girl"), archetype: "faction-bridge", residence: "town", role: "Teen", sanity: 45, trust: 45, is_rememberer: 0,
        secret: Some("Has a crush on Wren Adisa"),
        hook:   Some("Conduit between factions; knows things she shouldn't") },
    NpcSeed { id: "dom_petersen", name: "Dom Petersen", age: Some(36), gender: Some("Man"), archetype: "fixer", residence: "colony_house", role: "Engineer, bus arrival", sanity: 55, trust: 55, is_rememberer: 0,
        secret: Some("Genuinely believes he can build a working radio"),
        hook:   Some("Spends every spare hour on it") },
    NpcSeed { id: "loretta_voss", name: "Loretta Voss", age: Some(32), gender: Some("Woman"), archetype: "painful-reunion", residence: "colony_house", role: "Rico's ex-wife", sanity: 40, trust: 50, is_rememberer: 0,
        secret: Some("Arrived two months before Rico; both thought the other dead"),
        hook:   Some("The reunion was not joyful") },
    NpcSeed { id: "the_stranger", name: "The Stranger", age: None, gender: None, archetype: "voices-arc", residence: "wanderer", role: "Lives in the woods", sanity: 50, trust: 0, is_rememberer: 0,
        secret: Some("Hears voices; the voices have started naming the player"),
        hook:   Some("Arrives with a gift; disappears before questions") },
    NpcSeed { id: "bea_holm", name: "Bea Holm", age: Some(6), gender: Some("Girl"), archetype: "child-special", residence: "town", role: "Child", sanity: 70, trust: 80, is_rememberer: 0,
        secret: Some("Talks to Old Ren as though they are the same age"),
        hook:   Some("May be one of the dead returned; this is unconfirmed") },
    NpcSeed { id: "augustin_roy", name: "Augustin Roy", age: Some(48), gender: Some("Man"), archetype: "chef", residence: "colony_house", role: "Chef", sanity: 60, trust: 60, is_rememberer: 0,
        secret: Some("Was driving to scatter his daughter's ashes when the road turned"),
        hook:   Some("Cooks for everyone on the bad days") },
    NpcSeed { id: "verena_schiff", name: "Verena Schiff", age: Some(39), gender: Some("Woman"), archetype: "pharmacist", residence: "town", role: "Pharmacist", sanity: 55, trust: 60, is_rememberer: 0,
        secret: Some("Rations medicine and lies about the quantities"),
        hook:   Some("Compassionate liar") },
    NpcSeed { id: "hap_donnelly", name: "Hap Donnelly", age: Some(71), gender: Some("Man"), archetype: "the-broken", residence: "town", role: "Original-era resident", sanity: 25, trust: 30, is_rememberer: 0,
        secret: Some("Has been here sixty-odd years; was there when the children died"),
        hook:   Some("Knows nearly everything; will say almost none of it") },
    NpcSeed { id: "tia_mendez", name: "Tia Mendez", age: Some(33), gender: Some("Woman"), archetype: "lawyer", residence: "town", role: "Lawyer, bus arrival", sanity: 55, trust: 55, is_rememberer: 0,
        secret: Some("Organised a 'fair' exile in Year 1; the exile died that night"),
        hook:   Some("Carries the guilt like furniture") },
];
